version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Debug
  - Release

before_build:
  - cmd: nuget restore

build_script:
  - msbuild /t:PackageForAndroid /t:Clean
  - msbuild /t:PackageForAndroid /t:Build

artifacts:
  - path: '**\*.apk'
    name: apks
    type: File
